

[build]
  command = "npm run build"
  publish = ".next"
functions = "functions"
[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/bichon1/*"
  to = "/functions/bichon.js"
  status = 301
  force=true
  
  

