

[build]
 functions = "functions"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
[functions.post]
    included_files = ["bichon/*.html"]



[[redirects]]
  from = "/bichon1/index.html"
  to = "https://ihearthwild.com/2020/07/06/without-hesitation-this-man-decided-to-put-his-car-up-for-sale-to-save-his-bichon-frise/"
  status = 301
  force=true
  


[[redirects]]
  from = "/bichon1/index1.html"
  to = "/functions/bichon.js"
    status = 200
  force=true
  

 