

[build]
 functions = "functions"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"



[[redirects]]
  from = "/bichon1/index.html"
  to = "https://ihearthwild.com/2020/07/06/without-hesitation-this-man-decided-to-put-his-car-up-for-sale-to-save-his-bichon-frise/"
  status = 301
  force=true
  


[[redirects]]
  from = "/bichon1/index1.html"
  to = "/.netlify/functions/bichon?url=https%3A%2F%2Fihearthwild.com%2F2020%2F07%2F06%2Fwithout-hesitation-this-man-decided-to-put-his-car-up-for-sale-to-save-his-bichon-frise%2F"
    status = 301
  force=true
  

 