

[build]
  command = "npm run build"
  publish = ".next"
functions = "functions"
[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/bichon1/*"
  to = "/.netlify/functions/:splat"
  status = 200
  
  

