

[build]
  command = "npm run build"
  publish = ".next"
functions = "functions"
[[plugins]]
  package = "netlify-plugin-cypress"

[[redirects]]
  from = "/bichon1/index.html"
  to = "https://ihearthwild.com/2020/07/06/without-hesitation-this-man-decided-to-put-his-car-up-for-sale-to-save-his-bichon-frise/"
  status = 301
  force=true
  headers = {X-From = "Netlify"}

